In [3]:
import numpy as np
from scipy.linalg import solve_continuous_lyapunov, cholesky, svd

np.set_printoptions(precision=4, suppress=True)

A = np.array([
    [-3, 5, 4, 0, 0],
    [0, -4, 2, 0, 1],
    [2, 0, -5, 1, 0],
    [-2, 3, 0, -8, 1],
    [2, 0, 3, 0, -9]
], dtype=float)

B = np.ones((5,1), dtype=float)
C = np.array([[3,1,0,1,0]], dtype=float)

print("A =\n", A)
print("\nB =\n", B)
print("\nC =\n", C)

Wc = solve_continuous_lyapunov(A, -B @ B.T)
Wo = solve_continuous_lyapunov(A.T, -C.T @ C)

print("\n=== Controllability Gramian Wc ===\n", Wc)
print("\n=== Observability Gramian Wo ===\n", Wo)

Rc = cholesky(Wc, lower=True)
Ro = cholesky(Wo, lower=True)

print("\n=== Cholesky factor Rc (Wc = Rc Rc^T) ===\n", Rc)
print("\n=== Cholesky factor Ro (Wo = Ro Ro^T) ===\n", Ro)

M = Ro.T @ Rc
U, Sigma, Vt = svd(M)

print("\n=== Matrix M = Ro^T Rc ===\n", M)
print("\n=== Singular values (Hankel singular values) Sigma ===\n", Sigma)
print("\n=== Left singular vectors U ===\n", U)
print("\n=== Right singular vectors V^T ===\n", Vt)

Sigma_sqrt_inv = np.diag(1.0 / np.sqrt(Sigma))
T = Sigma_sqrt_inv @ U.T @ Ro.T     
Ti = Rc @ Vt.T @ Sigma_sqrt_inv     

print("\n=== Balancing transformation T ===\n", T)
print("\n=== Inverse transformation T^{-1} ===\n", Ti)

Ab = T @ A @ Ti
Bb = T @ B
Cb = C @ Ti

print("\n=== Balanced A (Ab) ===\n", Ab)
print("\n=== Balanced B (Bb) ===\n", Bb)
print("\n=== Balanced C (Cb) ===\n", Cb)

Wc_bal = T @ Wc @ T.T
Wo_bal = np.linalg.inv(T).T @ Wo @ np.linalg.inv(T)

print("\n=== Balanced controllability Gramian Wc_bal ===\n", Wc_bal)
print("\n=== Balanced observability Gramian Wo_bal ===\n", Wo_bal)


A =
 [[-3.  5.  4.  0.  0.]
 [ 0. -4.  2.  0.  1.]
 [ 2.  0. -5.  1.  0.]
 [-2.  3.  0. -8.  1.]
 [ 2.  0.  3.  0. -9.]]

B =
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]]

C =
 [[3. 1. 0. 1. 0.]]

=== Controllability Gramian Wc ===
 [[45.123  13.029  17.431  -4.1903 15.9569]
 [13.029   3.8202  5.0708 -1.1269  4.6391]
 [17.431   5.0708  6.7596 -1.5642  6.1871]
 [-4.1903 -1.1269 -1.5642  0.508  -1.4356]
 [15.9569  4.6391  6.1871 -1.4356  5.6639]]

=== Observability Gramian Wo ===
 [[26.3084 36.282  37.6273  4.9498  4.5351]
 [36.282  50.5574 52.7153  6.7732  6.3491]
 [37.6273 52.7153 55.1718  7.0038  6.6397]
 [ 4.9498  6.7732  7.0038  0.938   0.8442]
 [ 4.5351  6.3491  6.6397  0.8442  0.7993]]

=== Cholesky factor Rc (Wc = Rc Rc^T) ===
 [[ 6.7174  0.      0.      0.      0.    ]
 [ 1.9396  0.2411  0.      0.      0.    ]
 [ 2.5949  0.1564  0.0387  0.      0.    ]
 [-0.6238  0.3445  0.0154  0.0039  0.    ]
 [ 2.3755  0.1313  0.0615  0.0038  0.0004]]

=== Cholesky factor Ro (Wo = Ro Ro^T) ===
 [[ 5.1292